version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: watermaji_postgres_prod
    environment:
      POSTGRES_DB: watermaji
      POSTGRES_USER: watermaji_user
      POSTGRES_PASSWORD: watermaji_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/db/init:/docker-entrypoint-initdb.d
    networks:
      - watermaji_network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: watermaji_mongodb_prod
    environment:
      MONGO_INITDB_DATABASE: watermaji_logs
      MONGO_INITDB_ROOT_USERNAME: watermaji_admin
      MONGO_INITDB_ROOT_PASSWORD: watermaji_admin_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - watermaji_network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: watermaji_redis_prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - watermaji_network

  # Backend API
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: watermaji_backend_prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgresql://postgres:AmxMusfbUShLtUlzrebSKOyqBQHniyud@trolley.proxy.rlwy.net:48632/railway
      - POSTGRES_PORT=5432
      - POSTGRES_DB=railway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AmxMusfbUShLtUlzrebSKOyqBQHniyud
      - MONGODB_URI=mongodb://mongodb:27017/watermaji_logs
      - REDIS_HOST=redis
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004,http://localhost:3005,http://frontend:3000,http://host.docker.internal:3000
      - JWT_SECRET=746971f560a53d639db8b3985b2bb295
      - JWT_ACCESS_TOKEN_EXPIRY=15m
      - JWT_REFRESH_TOKEN_EXPIRY=7d
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - watermaji_network
    restart: unless-stopped

  # Frontend Dashboard
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: watermaji_frontend_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - watermaji_network
    restart: unless-stopped

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: watermaji_pgadmin_prod
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@watermaji.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - watermaji_network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:

networks:
  watermaji_network:
    driver: bridge
